version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    environment:
      NO_IPS_EXCEPTHOOK: True
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: echo $NO_IPS_EXCEPTHOOK
      # assume git is configured
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"

      - run: python -m unittest
