version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    environment:
      NO_IPS_EXCEPTHOOK: True
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: echo $NO_IPS_EXCEPTHOOK
      - run: python -m unittest
