---
# This is a comment and will be ignored. Same for empty lines.

# The top YAML-element is a list. Entries are strings or dicts.
# The following two list entries are just simple literal strings
# (one url per line):

- https://pad.url1.org/p/some-pad/export/txt
- https://pad.url1.org/p/some-other-pad/export/txt

# The next url needs some additional information.
# It is thus stored as yaml-dictionary.

- "https://pad.url1.org/p/some-third-pad/export/txt":
    name: explicit_filename.txt
    key2: value2

# yet another pad
- https://etherpad.wikimedia.org/p/padstogit-testing-pad

# this is no etherpad but works as well:
- "https://demo.hedgedoc.org/u5Epi_JmSrGaRRMx-VRiXQ/download":
    name: hedgedoc-demo.md
