---
# This is a comment and will be ignored. Same for empty lines.

# The top YAML-element is a list. Entries are strings or dicts.
# The following two list entries are just simple literal strings
# (one url per line):

- https://pad.url1.org/p/some-pad
- https://pad.url1.org/p/some-other-pad

# The next url needs some additional information.
# It is thus stored as yaml-dictionary.

- "https://pad.url1.org/p/some-third-pad":
    name: explicit_filename.txt
    key2: value2

- https://pad.url2.org/p/yet-another-pad
