---
# This is a comment and will be ignored. Same for empty lines.

# The top YAML-element is a list. Entries are strings or dicts.
# The following two list entries are just simple literal strings
# (one url per line):

- https://etherpad.wikimedia.org/p/padstogit_testpad1
- "https://etherpad.wikimedia.org/p/padstogit_testpad2":
    name: renamed_testpad.md
- https://etherpad.wikimedia.org/p/padstogit_testpad3
